name: Configure GitHub Pages

on:
  workflow_call:
    inputs:
      environment:
        description: 'The GitHub Pages environment to configure'
        required: true
        type: string
        default: 'github-pages'

jobs:
  configure-pages:
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
    
    steps:
      - name: Configure GitHub Pages
        uses: actions/configure-pages@v4
        with:
          # 静态站点生成器的输出目录
          static-site-generator: vuepress
          # 构建输出目录
          path: './docs/.vuepress/dist'
          # 发布源（gh-pages 分支）
          publish_branch: gh-pages
          # 发布目录（根目录）
          publish_dir: .